export { default as Contador } from './contador/Contador';
export { default as EjemploOnChange } from './EjemploOnChange/EjemploOnChange';
export { default as EjemploOnClick } from './EjemploOnClick/EjemploOnClick';
export { default as EjemploOnSubmit } from './EjemploOnSubmit/EjemploOnSubmit';
export { default as EjemploUseEffect } from './EjemploUseEffect/EjemploUseEffect';
export * from './GeneralWrapper/GeneralWrapper';
export * from './index';
export { default as Nuevo } from './Nuevo/Nuevo';
export { default as Ref } from './ref/Ref';
export { default as SmallWrapper } from './SmallWrapper/SmallWrapper';
